package Modelos;
// Generated 28-feb-2025 19:00:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Autores generated by hbm2java
 */
public class Autores  implements java.io.Serializable {


     private Integer id;
     private String autor;
     private Date fechaNacimiento;
     private String nacionalidad;
     private Set libroses = new HashSet(0);

    public Autores() {
    }

	
    public Autores(String autor) {
        this.autor = autor;
    }
    public Autores(String autor, Date fechaNacimiento, String nacionalidad, Set libroses) {
       this.autor = autor;
       this.fechaNacimiento = fechaNacimiento;
       this.nacionalidad = nacionalidad;
       this.libroses = libroses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Set getLibroses() {
        return this.libroses;
    }
    
    public void setLibroses(Set libroses) {
        this.libroses = libroses;
    }




}


