package Modelos;
// Generated 28-feb-2025 19:00:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer id;
     private String genero;
     private Set libroses = new HashSet(0);

    public Genero() {
    }

	
    public Genero(String genero) {
        this.genero = genero;
    }
    public Genero(String genero, Set libroses) {
       this.genero = genero;
       this.libroses = libroses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Set getLibroses() {
        return this.libroses;
    }
    
    public void setLibroses(Set libroses) {
        this.libroses = libroses;
    }




}


