package Modelos;
// Generated 28-feb-2025 19:00:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private Integer id;
     private Autores autores;
     private Genero genero;
     private String isbn;
     private String titulo;
     private Date fechaPublicacion;
     private BigDecimal precioUnidad;
     private int stock;
     private Set ventases = new HashSet(0);

    public Libros() {
    }

	
    public Libros(String isbn, String titulo, BigDecimal precioUnidad, int stock) {
        this.isbn = isbn;
        this.titulo = titulo;
        this.precioUnidad = precioUnidad;
        this.stock = stock;
    }
    public Libros(Autores autores, Genero genero, String isbn, String titulo, Date fechaPublicacion, BigDecimal precioUnidad, int stock, Set ventases) {
       this.autores = autores;
       this.genero = genero;
       this.isbn = isbn;
       this.titulo = titulo;
       this.fechaPublicacion = fechaPublicacion;
       this.precioUnidad = precioUnidad;
       this.stock = stock;
       this.ventases = ventases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Autores getAutores() {
        return this.autores;
    }
    
    public void setAutores(Autores autores) {
        this.autores = autores;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public BigDecimal getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(BigDecimal precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


