package Modelos;
// Generated 28-feb-2025 19:00:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer id;
     private Facturas facturas;
     private Libros libros;
     private int cantidad;
     private BigDecimal precioUnidad;
     private BigDecimal precioVenta;
     private BigDecimal importeTotal;

    public Ventas() {
    }

	
    public Ventas(int cantidad, BigDecimal precioUnidad) {
        this.cantidad = cantidad;
        this.precioUnidad = precioUnidad;
    }
    public Ventas(Facturas facturas, Libros libros, int cantidad, BigDecimal precioUnidad, BigDecimal precioVenta, BigDecimal importeTotal) {
       this.facturas = facturas;
       this.libros = libros;
       this.cantidad = cantidad;
       this.precioUnidad = precioUnidad;
       this.precioVenta = precioVenta;
       this.importeTotal = importeTotal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public Libros getLibros() {
        return this.libros;
    }
    
    public void setLibros(Libros libros) {
        this.libros = libros;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(BigDecimal precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public BigDecimal getImporteTotal() {
        return this.importeTotal;
    }
    
    public void setImporteTotal(BigDecimal importeTotal) {
        this.importeTotal = importeTotal;
    }




}


